import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../tokens/colors.dart';
import '../tokens/radius.dart';
import '../tokens/typography.dart';
import 'theme_extensions.dart';

/// Builds a complete [ThemeData] so a white-labelled school re-themes with
/// one value ([primaryColor] = their blue/500 override).
///
/// M3: color roles are generated by `ColorScheme.fromSeed` — Flutter's own
/// Material Color Utilities (HCT) engine, the same one Google Material uses —
/// rather than hand-picked. The brand deliberately uses THREE hues, not one
/// (institutional blue, amber CTA, cyan info), so we seed three schemes and
/// graft amber's/cyan's primary role onto our secondary/tertiary roles. A
/// single-seed scheme would auto-derive a desaturated blue for "secondary",
/// which would quietly kill the amber accent identity everywhere it's used.
///
/// Light-only for v1 — a half-tuned dark mode looks more amateur than none.
abstract final class AppTheme {
  static ThemeData build([Color? primaryColor]) {
    final primary = primaryColor ?? AppColors.blue500;

    final baseScheme = ColorScheme.fromSeed(
      seedColor: primary,
      brightness: Brightness.light,
    );
    final accentScheme = ColorScheme.fromSeed(
      seedColor: AppColors.amber500,
      brightness: Brightness.light,
    );
    final tertiaryScheme = ColorScheme.fromSeed(
      seedColor: AppColors.cyan500,
      brightness: Brightness.light,
    );

    final colorScheme = baseScheme.copyWith(
      secondary: accentScheme.primary,
      onSecondary: accentScheme.onPrimary,
      secondaryContainer: accentScheme.primaryContainer,
      onSecondaryContainer: accentScheme.onPrimaryContainer,
      tertiary: tertiaryScheme.primary,
      onTertiary: tertiaryScheme.onPrimary,
      tertiaryContainer: tertiaryScheme.primaryContainer,
      onTertiaryContainer: tertiaryScheme.onPrimaryContainer,
    );

    final ext = AppThemeExtension.fromScheme(
      colorScheme,
      accentScheme,
      tertiaryScheme,
    );

    return ThemeData(
      useMaterial3: true,
      brightness: Brightness.light,
      colorScheme: colorScheme,
      scaffoldBackgroundColor: ext.appBackground,
      textTheme: AppTypography.textTheme(primary: ext.textPrimary),
      extensions: <ThemeExtension<dynamic>>[
        ext,
        const AppDensityExtension(density: AppDensity.comfortable),
      ],
      appBarTheme: AppBarTheme(
        elevation: 0,
        scrolledUnderElevation: 0,
        backgroundColor: ext.surface,
        foregroundColor: ext.textPrimary,
        surfaceTintColor: Colors.transparent,
        systemOverlayStyle: SystemUiOverlayStyle.dark,
        titleTextStyle: AppTypography.h1(color: ext.textPrimary),
        toolbarHeight: 56,
        shape: Border(
          bottom: BorderSide(color: ext.border, width: 1),
        ),
      ),
      dividerTheme: DividerThemeData(
        color: ext.border,
        thickness: 1,
        space: 1,
      ),
      // M3 "tonal elevation": a filled card is a step UP the surface-container
      // scale, not a shadow. No border — the tonal step against the scaffold
      // background is what reads as "raised" in Material 3.
      cardTheme: CardThemeData(
        color: ext.surfaceAlt,
        elevation: 0,
        margin: EdgeInsets.zero,
        shape: RoundedRectangleBorder(borderRadius: AppRadius.borderMd),
      ),
      chipTheme: ChipThemeData(
        backgroundColor: ext.surfaceContainerHigh,
        labelStyle: AppTypography.caption(color: ext.textSecondary),
        shape: RoundedRectangleBorder(borderRadius: AppRadius.borderFull),
        side: BorderSide.none,
      ),
      inputDecorationTheme: InputDecorationTheme(
        filled: true,
        fillColor: ext.surfaceAlt,
        contentPadding: const EdgeInsets.symmetric(horizontal: 12, vertical: 14),
        border: OutlineInputBorder(
          borderRadius: AppRadius.borderSm,
          borderSide: BorderSide(color: ext.borderStrong, width: 1),
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: AppRadius.borderSm,
          borderSide: BorderSide(color: ext.borderStrong, width: 1),
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: AppRadius.borderSm,
          borderSide: BorderSide(color: primary, width: 2),
        ),
        errorBorder: OutlineInputBorder(
          borderRadius: AppRadius.borderSm,
          borderSide: BorderSide(color: ext.danger, width: 2),
        ),
        focusedErrorBorder: OutlineInputBorder(
          borderRadius: AppRadius.borderSm,
          borderSide: BorderSide(color: ext.danger, width: 2),
        ),
        disabledBorder: OutlineInputBorder(
          borderRadius: AppRadius.borderSm,
          borderSide: BorderSide(color: ext.borderStrong, width: 1),
        ),
        hintStyle: AppTypography.body(color: ext.placeholder),
        errorStyle: AppTypography.bodySmall(color: ext.dangerText),
        labelStyle: AppTypography.label(color: ext.textSecondary),
      ),
      snackBarTheme: SnackBarThemeData(
        // M3 inverse-surface — a snackbar is deliberately the one place the
        // "opposite" tone appears, so it reads instantly against the page.
        backgroundColor: colorScheme.inverseSurface,
        contentTextStyle:
            AppTypography.body(color: colorScheme.onInverseSurface),
        actionTextColor: colorScheme.inversePrimary,
        behavior: SnackBarBehavior.floating,
        shape: RoundedRectangleBorder(borderRadius: AppRadius.borderMd),
      ),
      bottomNavigationBarTheme: BottomNavigationBarThemeData(
        backgroundColor: ext.surface,
        selectedItemColor: primary,
        unselectedItemColor: ext.textTertiary,
        type: BottomNavigationBarType.fixed,
        elevation: 0,
      ),
      navigationBarTheme: NavigationBarThemeData(
        backgroundColor: ext.surface,
        surfaceTintColor: Colors.transparent,
        indicatorColor: ext.primaryContainer,
        elevation: 0,
        height: 64,
        labelBehavior: NavigationDestinationLabelBehavior.alwaysShow,
      ),
      dialogTheme: DialogThemeData(
        backgroundColor: ext.surfaceContainerHigh,
        elevation: 0,
        shape: RoundedRectangleBorder(borderRadius: AppRadius.borderXl),
      ),
      bottomSheetTheme: BottomSheetThemeData(
        backgroundColor: ext.surfaceContainerHigh,
        elevation: 0,
        shape: const RoundedRectangleBorder(borderRadius: AppRadius.sheetTop),
        showDragHandle: true,
      ),
      // Suppress Material purple defaults.
      splashFactory: InkRipple.splashFactory,
    );
  }
}
